# Default values for iorad.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1

revision:

src:
  image: iorad/src
  pullPolicy: IfNotPresent

app:
  image: iorad/iorad-dev-app
  pullPolicy: IfNotPresent

webpack:
  replicaCount: 1

dev:
  image: iorad/iorad-dev-node
  pullPolicy: IfNotPresent

nameOverride: ""

fullnameOverride: ""

lifecycle: {}

livenessProbe: {}

configMapEnv:
  LOGGING_LEVEL: debug
  PORT: 3000
  WEBPACK_PORT: 3001
  API_PORT: 3030

secretEnv: {}

volumes:
- name: storage
  persistentVolumeClaim:
    claimName: iorad-storage-dev
    existing: true

service:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: dev
    protocol: TCP
    name: dev

webpackService:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: webpack
    protocol: TCP
    name: webpack

ingress: {}

ingressRewrite: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  enabled: false
  imageTag: 5.7
  port: 3306

migration:
  enabled: false

redis:
  enabled: true
  architecture: standalone

maildev:
  enabled: false
