{{- $fullname := include "iorad.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ include "iorad.name" . }}
    helm.sh/chart: {{ include "iorad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "iorad.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "iorad.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - name: wait-for-db
        image: mysql:{{ .Values.mysql.imageTag }}
        command:
        - sh
        - -c
        - |
          set -ex
          # create folders if not exist
          mkdir -p /mnt/storage/iorad/cache
          mkdir -p /mnt/storage/iorad/sitemaps
          # TODO(hoatle): use env vars instead of hard-code here
          mkdir -p /mnt/storage/iorad/crypto/tutorials
          mkdir -p /mnt/storage/iorad/static
          # TODO(hoatle): retry + timeout support
          echo "Waiting for mysqld to be ready (accepting connections)"
          until mysql -h $MYSQL_HOST -u $MYSQL_USER -p${MYSQL_PASSWORD} -e "SELECT 1"; do sleep 5; done
        {{- if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ $fullname }}-db
        - secretRef:
            name: {{ $fullname }}-db
      containers:
      - name: iorad
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.command }}
        command:
        - sh
        - -c
        - |
{{ .Values.command | indent 10 }}
        {{- end }}
        {{- if .Values.lifecycle }}
        lifecycle:
{{ toYaml .Values.lifecycle | indent 10 }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
        env:
        - name: REVISION # for auto-restarting the pod
          value: {{ .Values.revision | quote }}
        envFrom:
        - configMapRef:
            name: {{ $fullname }}
        - secretRef:
            name: {{ $fullname }}
        - configMapRef:
            name: {{ $fullname }}-db
        - secretRef:
            name: {{ $fullname }}-db
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.volumes }}
      volumes:
      {{- range .Values.volumes }}
      {{- if .persistentVolumeClaim }}
      - name: {{ .name }}
        persistentVolumeClaim:
          {{- if .persistentVolumeClaim.existing }}
          claimName: {{ .persistentVolumeClaim.claimName }}
          {{- else }}
          claimName: {{ $fullname }}-{{ .persistentVolumeClaim.claimName }}
          {{- end }}
          readOnly: {{ default false .persistentVolumeClaim.readOnly }}
      {{- else }}
      - {{ . | toYaml | nindent 8 | trim }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
    {{- end }}
