{{- if .Values.maildev.enabled -}}
{{- $fullName := include "iorad.fullname" . -}}
{{- $ingressPath := .Values.maildev.ingress.path -}}
{{- $kubeVersion  := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-maildev
  labels:
    app.kubernetes.io/name: {{ include "iorad.name" . }}-maildev
    helm.sh/chart: {{ include "iorad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.maildev.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.maildev.ingress.tls }}
  tls:
  {{- range .Values.maildev.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.maildev.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- if semverCompare ">=1.19-0" $kubeVersion }}
        - path: {{ $ingressPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-maildev
              port:
                name: http
        {{- else }}
        - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-maildev
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
