apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iorad-storage-develop
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi