apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iorad-cdn.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "iorad-cdn.name" . }}
    helm.sh/chart: {{ include "iorad-cdn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
{{ $.Files.Get "config/nginx.conf" | indent 4 }}
  cdn.conf: |
{{ .Values.cdnConf | indent 4 }}
