{{- $fullname := include "iorad-cdn.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ include "iorad-cdn.name" . }}
    helm.sh/chart: {{ include "iorad-cdn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "iorad-cdn.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "iorad-cdn.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: iorad-cdn
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.command }}
        command:
        - sh
        - -c
        - |
{{ .Values.command | indent 10 }}
        {{- end }}
        {{- if .Values.lifecycle }}
        lifecycle:
{{ toYaml .Values.lifecycle | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: config-nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: config-cdn
          mountPath: /etc/nginx/conf.d/cdn.conf
          subPath: cdn.conf
        {{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 8 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
        env:
        - name: REVISION # for auto-restarting the pod
          value: {{ .Values.revision | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: config-nginx
        configMap:
          name: {{ $fullname }}-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: config-cdn
        configMap:
          name: {{ $fullname }}-config
          items:
          - key: cdn.conf
            path: cdn.conf
    {{- if .Values.volumes }}
      {{- range .Values.volumes }}
      {{- if .persistentVolumeClaim }}
      - name: {{ .name }}
        persistentVolumeClaim:
          {{- if .persistentVolumeClaim.existing }}
          claimName: {{ .persistentVolumeClaim.claimName }}
          {{- else }}
          claimName: {{ $fullname }}-{{ .persistentVolumeClaim.claimName }}
          readOnly: {{ default false .persistentVolumeClaim.readOnly }}
          {{- end }}
      {{- else }}
      - {{ . | toYaml | nindent 8 | trim }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
    {{- end }}
