{{- $fullname := include "iorad-dev.fullname" . -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullname }}-cleanup
  labels:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    helm.sh/chart: {{ include "iorad-dev.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    # "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name: {{ $fullname }}-cleanup
      labels:
        app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: cleanup
        image: "nginx:alpine"
        imagePullPolicy: "IfNotPresent"
        command:
        - sh
        - -c
        - |
          mkdir -p /opt/app # if not exists
          test -f /opt/app/.src-copied && rm /opt/app/.src-copied
          test -f /opt/app/node/.npm-installed && rm /opt/app/node/.npm-installed
          test -f /opt/app/node/webpack-assets.json && rm /opt/app/node/webpack-assets.json
          test -f /opt/app/node/static/downloadtutorials/html/assets/styles/player/flat-theme/style.css && rm /opt/app/node/static/downloadtutorials/html/assets/styles/player/flat-theme/style.css
          echo "clean up done"
        volumeMounts:
        - mountPath: /opt/app
          name: storage
          subPath: iorad
      volumes:
      {{- range .Values.volumes }}
      {{- if .persistentVolumeClaim }}
      - name: {{ .name }}
        persistentVolumeClaim:
          {{- if .persistentVolumeClaim.existing }}
          claimName: {{ .persistentVolumeClaim.claimName }}
          {{- else }}
          claimName: {{ $fullname }}-{{ .persistentVolumeClaim.claimName }}
          {{- end }}
          readOnly: {{ default false .persistentVolumeClaim.readOnly }}
      {{- else }}
      - {{ . | toYaml | nindent 8 | trim }}
      {{- end }}
      {{- end }}
