apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iorad-dev.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    helm.sh/chart: {{ include "iorad-dev.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  MYSQL_HOST: {{ include "iorad-dev.databaseHost" . | quote }}
  MYSQL_PORT: {{ $.Values.mysql.port | quote }}
