{{- if .Values.ingressRewrite.enabled -}}
{{- $fullName := include "iorad-dev.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rewrite
  labels:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    helm.sh/chart: {{ include "iorad-dev.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingressRewrite.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingressRewrite.tls }}
  tls:
  {{- range .Values.ingressRewrite.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingressRewrite.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .http.paths }}
      - backend:
          serviceName: {{ .backend.serviceName }}
          servicePort: {{ .backend.servicePort }}
        path: {{ .path }}
      {{- end }}
  {{- end }}
{{- end }}
