apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iorad-dev.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    helm.sh/chart: {{ include "iorad-dev.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ default "" $val | toString | b64enc | quote }}
{{- end }}
