apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iorad-dev.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    helm.sh/chart: {{ include "iorad-dev.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{ if $.Values.mysql.mysqlUser }}
  MYSQL_USER: {{ $.Values.mysql.mysqlUser | b64enc | quote }}
{{ end }}
{{ if $.Values.mysql.mysqlPassword }}
  MYSQL_PASSWORD: {{ $.Values.mysql.mysqlPassword | b64enc | quote }}
{{ end }}
{{ if $.Values.mysql.mysqlDatabase }}
  MYSQL_DATABASE: {{ $.Values.mysql.mysqlDatabase | b64enc | quote }}
{{ end }}
  DATABASE_URL: {{ include "iorad-dev.databaseUrl" . | b64enc | quote }}
