apiVersion: v1
kind: Service
metadata:
  name: {{ include "iorad-dev.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    helm.sh/chart: {{ include "iorad-dev.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "iorad-dev.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
