# Default values for iorad-cdn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

revision: ""

image:
  repository: nginx
  tag: alpine-perl
  pullPolicy: IfNotPresent

nameOverride: ""

fullnameOverride: ""

cdnConf: ""

livenessProbe: {}

volumeMounts: {}

volumes: {}

service:
  type: ClusterIP
  port: 80

ingress: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
